#!/usr/bin/python2
import os

home  = os.getenv("HOME")

lines =  open("%s/.messages" % home).readlines()
if len(lines) > 0:
  print "\005{g}PM from: \005{Y}%s\005{B}" % lines[0].rstrip()
  os.system("> %s/.messages" % home)
else:
  print "\005{g}No new messages\005{B}"
