#!/bin/sh

if [ $(xrandr | grep ' connected' |wc -l) = 1 ]; then
  bspc monitor -d I II III IV V VI VII VIII IX X
else
  xrandr --output LVDS1 --mode 1366x768
  xrandr --output VGA1 --mode 1920x1080 --right-of LVDS1

  bspc monitor LVDS1 -d I II III IV V
  bspc monitor VGA1 -d VI VII VIII IX X
fi

bspc config border_width 0
bspc config window_gap 20
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config normal_border_color "#504339"
bspc config active_border_color "#504339"
bspc config focused_border_color "#605655"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#504339"
