#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config normal_border_color "#504339"
bspc config active_border_color "#504339"
bspc config focused_border_color "#605655"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#504339"
